[package]
name = "country-geocoder"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.23.0"
geojson = { version = "0.24.0", features = ["geo-types"] }
serde = { version = "1", features = ["derive"] }
